In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import datetime
import warnings
warnings.filterwarnings("ignore")

In [2]:
versoes = {'Pandas':pd.__version__, 'Numpy':np.__version__, 'Seaborn':sns.__version__}
versoes

{'Pandas': '2.1.4', 'Numpy': '1.26.4', 'Seaborn': '0.12.2'}

In [3]:
with open('microdados_enem_2023\DADOS\MICRODADOS_ENEM_2023.csv') as f:
    print(f)

<_io.TextIOWrapper name='microdados_enem_2023\\DADOS\\MICRODADOS_ENEM_2023.csv' mode='r' encoding='cp1252'>


In [4]:
# Define o número máximo de colunas a serem exibidas
pd.set_option('display.max_columns', 80)

# Define o número de casas decimais para valores em ponto flutuante
pd.set_option('display.precision', 2)

In [5]:
# Comeco
comeco = datetime.datetime.now()
print(comeco)

#df = pd.read_csv('DADOS\MICRODADOS_ENEM_2023.csv', encoding='cp1252', sep=';')
df = pd.read_csv('microdados_enem_2023\DADOS\MICRODADOS_ENEM_2023.csv', encoding='cp1252', sep=';')

# Final
final = datetime.datetime.now()
print(final)

tempo = final - comeco
tempo

2024-05-24 10:31:12.537833
2024-05-24 10:32:31.997786


datetime.timedelta(seconds=79, microseconds=459953)

# Informações Básicas do Dataframe

O Exame Nacional do Ensino Médio (ENEM) teve 3.933.955 inscritos, sendo 2.411.185 (61,29%) mulheres e 1.522.770 (38,71%) homens.t640

In [6]:
# Mostrar os primeiros dados do dataframe
df.head()

NU_INSCRICAO  NU_ANO  TP_FAIXA_ETARIA TP_SEXO  TP_ESTADO_CIVIL  \
0  210059085136    2023               14       M                2   
1  210059527735    2023               12       M                2   
2  210061103945    2023                6       F                1   
3  210060214087    2023                2       F                1   
4  210059980948    2023                3       F                1   

   TP_COR_RACA  TP_NACIONALIDADE  TP_ST_CONCLUSAO  TP_ANO_CONCLUIU  TP_ESCOLA  \
0            1                 1                1               17          1   
1            1                 0                1               16          1   
2            1                 1                1                0          1   
3            3                 1                2                0          2   
4            3                 1                2                0          2   

   TP_ENSINO  IN_TREINEIRO  CO_MUNICIPIO_ESC NO_MUNICIPIO_ESC  CO_UF_ESC  \
0        NaN             0               NaN              NaN        NaN   
1        NaN             0               NaN              NaN        NaN   
2        NaN             0               NaN              NaN        NaN   
3        1.0             0          2.30e+06        Fortaleza       23.0   
4        1.0             0          2.31e+06          Quixadá       23.0   

  SG_UF_ESC  TP_DEPENDENCIA_ADM_ESC  TP_LOCALIZACAO_ESC  TP_SIT_FUNC_ESC  \
0       NaN                     NaN                 NaN              NaN   
1       NaN                     NaN                 NaN              NaN   
2       NaN                     NaN                 NaN              NaN   
3        CE                     2.0                 1.0              1.0   
4        CE                     2.0                 1.0              1.0   

   CO_MUNICIPIO_PROVA NO_MUNICIPIO_PROVA  CO_UF_PROVA SG_UF_PROVA  \
0             5300108           Brasília           53          DF   
1             5300108           Brasília           53          DF   
2             4305108      Caxias do Sul           43          RS   
3             2304400          Fortaleza           23          CE   
4             2311306            Quixadá           23          CE   

   TP_PRESENCA_CN  TP_PRESENCA_CH  TP_PRESENCA_LC  TP_PRESENCA_MT  \
0               0               0               0               0   
1               0               0               0               0   
2               1               1               1               1   
3               1               1               1               1   
4               1               1               1               1   

   CO_PROVA_CN  CO_PROVA_CH  CO_PROVA_LC  CO_PROVA_MT  NU_NOTA_CN  NU_NOTA_CH  \
0          NaN          NaN          NaN          NaN         NaN         NaN   
1          NaN          NaN          NaN          NaN         NaN         NaN   
2       1221.0       1193.0       1204.0       1211.0       502.0       498.9   
3       1224.0       1192.0       1202.0       1214.0       459.0       508.5   
4       1222.0       1191.0       1201.0       1212.0       402.5       379.2   

   NU_NOTA_LC  NU_NOTA_MT                                TX_RESPOSTAS_CN  \
0         NaN         NaN                                            NaN   
1         NaN         NaN                                            NaN   
2       475.6       363.2  DBEBDCECCBCEBBBBDBABDDBBAABCBACDBACECCBAADEBB   
3       507.2       466.7  DEEBEACCCEBDDBDCCCAEEDCBAAADBCBEEEDCDAAECBEEC   
4       446.9       338.3  AECCEAACDEABEEECDBAEEAAADDEABCBCEBACEEDCBEABD   

                                 TX_RESPOSTAS_CH  \
0                                            NaN   
1                                            NaN   
2  ABDEADAADCDABDCADAEABCDDCBAADCCBEBCEBEBDBEAED   
3  DDAAEEBCCDEADBCDDCBAECABEBDEBDABECECEDCDDAEED   
4  CADEBCEDDEBCBAEBADDCECACADBDEBABDBDBEEDBBEADC   

                                 TX_RESPOSTAS_LC  \
0                                            NaN

In [7]:
# Dimmensão do dataframe
dim = df.shape
print(f'A tabela tem {dim[0]} milhões de linhas e {dim[1]} colunas')

A tabela tem 3933955 milhões de linhas e 76 colunas


In [8]:
# Informações do dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3933955 entries, 0 to 3933954
Data columns (total 76 columns):
 #   Column                  Dtype  
---  ------                  -----  
 0   NU_INSCRICAO            int64  
 1   NU_ANO                  int64  
 2   TP_FAIXA_ETARIA         int64  
 3   TP_SEXO                 object 
 4   TP_ESTADO_CIVIL         int64  
 5   TP_COR_RACA             int64  
 6   TP_NACIONALIDADE        int64  
 7   TP_ST_CONCLUSAO         int64  
 8   TP_ANO_CONCLUIU         int64  
 9   TP_ESCOLA               int64  
 10  TP_ENSINO               float64
 11  IN_TREINEIRO            int64  
 12  CO_MUNICIPIO_ESC        float64
 13  NO_MUNICIPIO_ESC        object 
 14  CO_UF_ESC               float64
 15  SG_UF_ESC               object 
 16  TP_DEPENDENCIA_ADM_ESC  float64
 17  TP_LOCALIZACAO_ESC      float64
 18  TP_SIT_FUNC_ESC         float64
 19  CO_MUNICIPIO_PROVA      int64  
 20  NO_MUNICIPIO_PROVA      object 
 21  CO_UF_PROVA             int64  

In [9]:
# Valores únicos do dataframe
df.nunique().reset_index()

index        0
0      NU_INSCRICAO  3933955
1            NU_ANO        1
2   TP_FAIXA_ETARIA       20
3           TP_SEXO        2
4   TP_ESTADO_CIVIL        5
..              ...      ...
71             Q021        2
72             Q022        5
73             Q023        2
74             Q024        5
75             Q025        2

[76 rows x 2 columns]

In [10]:
# Valores Duplicados
df.duplicated().sum().sum()

0

In [11]:
df['TP_SEXO'].value_counts()

TP_SEXO
F    2411185
M    1522770
Name: count, dtype: int64

In [12]:
df['TP_SEXO'].value_counts(normalize=True)*100

TP_SEXO
F    61.29
M    38.71
Name: proportion, dtype: float64

# Apagar Participantes Faltantes

Todos os candidatos que estiveram ausentes em alguma prova foram descartados, dessa forma será avaliada apenas aqueles que compareceram as 5 provas.  
Foram descartados 1.255.691 participantes que faltaram a no mínimo uma prova.

In [13]:
df = df.dropna(subset=['NU_NOTA_CN', 'NU_NOTA_CH', 'NU_NOTA_MT', 'NU_NOTA_LC', 'NU_NOTA_REDACAO'])
df.shape

(2678264, 76)

# Adicionar Coluna Nota Total e Média

Foi criada uma coluna com a soma das notas e outra com a média das notas.
Para calcular a média, foi utilizado peso 1 para todas as áreas.

In [14]:
df['W_Nota_Total'] = df['NU_NOTA_CN'] + df['NU_NOTA_CH'] + df['NU_NOTA_LC'] + df['NU_NOTA_MT'] + df['NU_NOTA_REDACAO']
df['W_Media'] = df['W_Nota_Total'] / 5
df.head()

NU_INSCRICAO  NU_ANO  TP_FAIXA_ETARIA TP_SEXO  TP_ESTADO_CIVIL  \
2   210061103945    2023                6       F                1   
3   210060214087    2023                2       F                1   
4   210059980948    2023                3       F                1   
9   210060801601    2023               11       M                1   
10  210059085130    2023                8       M                1   

    TP_COR_RACA  TP_NACIONALIDADE  TP_ST_CONCLUSAO  TP_ANO_CONCLUIU  \
2             1                 1                1                0   
3             3                 1                2                0   
4             3                 1                2                0   
9             1                 1                1                8   
10            3                 1                1                5   

    TP_ESCOLA  TP_ENSINO  IN_TREINEIRO  CO_MUNICIPIO_ESC NO_MUNICIPIO_ESC  \
2           1        NaN             0               NaN              NaN   
3           2        1.0             0          2.30e+06        Fortaleza   
4           2        1.0             0          2.31e+06          Quixadá   
9           1        NaN             0               NaN              NaN   
10          1        NaN             0               NaN              NaN   

    CO_UF_ESC SG_UF_ESC  TP_DEPENDENCIA_ADM_ESC  TP_LOCALIZACAO_ESC  \
2         NaN       NaN                     NaN                 NaN   
3        23.0        CE                     2.0                 1.0   
4        23.0        CE                     2.0                 1.0   
9         NaN       NaN                     NaN                 NaN   
10        NaN       NaN                     NaN                 NaN   

    TP_SIT_FUNC_ESC  CO_MUNICIPIO_PROVA NO_MUNICIPIO_PROVA  CO_UF_PROVA  \
2               NaN             4305108      Caxias do Sul           43   
3               1.0             2304400          Fortaleza           23   
4               1.0             2311306            Quixadá           23   
9               NaN             3505906           Batatais           35   
10              NaN             2408102              Natal           24   

   SG_UF_PROVA  TP_PRESENCA_CN  TP_PRESENCA_CH  TP_PRESENCA_LC  \
2           RS               1               1               1   
3           CE               1               1               1   
4           CE               1               1               1   
9           SP               1               1               1   
10          RN               1               1               1   

    TP_PRESENCA_MT  CO_PROVA_CN  CO_PROVA_CH  CO_PROVA_LC  CO_PROVA_MT  \
2                1       1221.0       1193.0       1204.0       1211.0   
3                1       1224.0       1192.0       1202.0       1214.0   
4                1       1222.0       1191.0       1201.0       1212.0   
9                1       1223.0       1194.0       1203.0       1213.0   
10               1       1221.0       1193.0       1204.0       1211.0   

    NU_NOTA_CN  NU_NOTA_CH  NU_NOTA_LC  NU_NOTA_MT  \
2        502.0       498.9       475.6       363.2   
3        459.0       508.5       507.2       466.7   
4        402.5       379.2       446.9       338.3   
9        564.7       630.3       610.4       680.2   
10       644.9       620.2       626.9       736.3   

                                  TX_RESPOSTAS_CN  \
2   DBEBDCECCBCEBBBBDBABDDBBAABCBACDBACECCBAADEBB   
3   DEEBEACCCEBDDBDCCCAEEDCBAAADBCBEEEDCDAAECBEEC   
4   AECCEAACDEABEEECDBAEEAAADDEABCBCEBACEEDCBEABD   
9   CBAACDDEDEDEBCDDBACEACECECCEBBDCBEAEABCDBEADB   
10  DBEEBDBBACDCABADCDAACECDBBDECDADBBECDCDDCEAAD   

                                  TX_RESPOSTAS_CH  \
2   ABDEADAADCDABDCADAEABCDDCBAADCCBEBCEBEBDBEAED   
3   DDAAEEBCCDEADBCDDCBAECABEBDEBDABECECEDCDDAEED   
4   CADEBCEDDEBCBAEBADDCECACADBDEBABDBDBEEDBBEADC   
9   ABCDCBCACDBEACEBAABADAEBAADCBADBCDCEBADCDAADE   
10  ACEEADAABCBAABEDBCDAECDCDBCBDAEEBDECAADDDCDDE   

          

# Análise da Teoria de Resposta ao Item (TRI)

|O TRI é uma metodologia estatística utilizada no ENEM para calcular as notas de forma mais precisa e justa. O TRI leva em consideração a dificuldade da questão, a discriminação e a possibilidade de acerto ao acaso. 
Para considerar a dificuldade da questão, que pode ser fácil, média ou difícil, o TRI leva em conta que questões mais difíceis têm menos acertos e questões mais fáceis têm mais acerto 

A discriminação é a capacidade da questão de diferenciar o nível de habilidade do candido.

A possibilidade de acerto ao acaso estima a chance de o estudante acertar a questão chu  
ndo.

Será feita uma análise mostrando a nota mínima, média e máxima para uma mesma quantidade de acertos. Além disso, será apresentada a diferença de pontos entre a maior e a menor nota, bem como o percentual que a maior nota supera   a menor.

In [15]:
def qtde_questoes_acertadas(str1, str2):
    tamanho = len(str1)
    contador = 0
    for i in range(tamanho):
        if str1[i] == str2[i]:
            contador += 1
    return contador

## 	Ciências da Natureza e suas Tecnologias

- A maior diferença de pontos está em 17 acertos, com 289,2;
- A maior porcentagem de diferença está em 15 acertos, com um total de 87%, ou seja, para uma mesma quantidade de acertos, a diferença entre a menor e a maior nota é, no máximo, de 87%;- 
A quantidade de questões mais acertadas frami 9, 10, 11, 12 e 13, sendo 11 acertos a que teve mais alunos, com um total de 294.27;
- de 14 estudantes acaramtou todas as questões da prova, tendo um total de 868,4 pon;
- 16.270 erraram todas as questões da prova.os.

In [16]:
df_notas_cn = df[['NU_INSCRICAO','TX_GABARITO_CN', 'TX_RESPOSTAS_CN', 'NU_NOTA_CN']]
df_notas_cn['Qtde_Questoes'] = df_notas_cn.apply(lambda row: qtde_questoes_acertadas(row['TX_GABARITO_CN'], row['TX_RESPOSTAS_CN']), axis=1)

minima = df_notas_cn.groupby('Qtde_Questoes')['NU_NOTA_CN'].min()
media = df_notas_cn.groupby('Qtde_Questoes')['NU_NOTA_CN'].mean()
maxima = df_notas_cn.groupby('Qtde_Questoes')['NU_NOTA_CN'].max()
diferenca = maxima - minima
porcentagem = (maxima / minima) - 1

notas_cn = {'Minima' : minima,
        'Média' :  media,
        'Máxima' : maxima,
        'Diferenca' : diferenca,
        'Porcentagegm_Diferenca' : porcentagem}

notas_cn = pd.DataFrame(notas_cn)
notas_cn

Minima   Média  Máxima  Diferenca  Porcentagegm_Diferenca
Qtde_Questoes                                                           
0                 0.0    2.05   323.3      323.3                     inf
1               322.4  338.31   374.0       51.6                    0.16
2               322.4  351.35   410.3       87.9                    0.27
3               323.4  363.98   440.9      117.5                    0.36
4               323.4  376.39   464.9      141.5                    0.44
5               323.4  388.74   492.8      169.4                    0.52
6               322.7  401.02   512.4      189.7                    0.59
7               318.3  414.31   527.3      209.0                    0.66
8               316.1  427.90   539.4      223.3                    0.71
9               320.3  442.76   550.6      230.3                    0.72
10              321.8  458.47   562.7      240.9                    0.75
11              324.4  474.87   575.9      251.5                    0.78
12              326.1  491.85   588.7      262.6                    0.81
13              327.3  509.37   598.1      270.8                    0.83
14              330.3  526.85   606.7      276.4                    0.84
15              327.6  543.99   613.8      286.2                    0.87
16              338.3  560.55   621.1      282.8                    0.84
17              339.1  576.12   628.3      289.2                    0.85
18              366.0  590.15   640.1      274.1                    0.75
19              363.6  602.84   646.4      282.8                    0.78
20              419.7  614.12   655.9      236.2                    0.56
21              463.7  624.25   659.8      196.1                    0.42
22              479.0  633.39   668.9      189.9                    0.40
23              504.6  641.83   672.6      168.0                    0.33
24              590.0  649.69   681.2       91.2                    0.15
25              600.2  657.44   687.2       87.0                    0.14
26              615.2  664.66   692.5       77.3                    0.13
27              630.0  671.71   699.6       69.6                    0.11
28              643.7  679.06   704.2       60.5                    0.09
29              649.6  685.95   714.0       64.4                    0.10
30              661.1  693.18   721.3       60.2                    0.09
31              667.5  700.32   727.7       60.2                    0.09
32              670.5  707.54   731.6       61.1                    0.09
33              686.3  715.26   742.7       56.4                    0.08
34              692.5  722.91   750.8       58.3                    0.08
35              700.0  731.05   761.2       61.2                    0.09
36              712.1  739.29   766.1       54.0                    0.08
37              719.4  747.98   778.3       58.9                    0.08
38              725.4  757.35   791.4       66.0                    0.09
39              738.3  767.26   798.1       59.8                    0.08
40              747.2  777.97   809.0       61.8                    0.08
41              763.0  790.79   816.5       53.5                    0.07
42              772.1  805.38   833.5       61.4                    0.08
43              783.4  823.94   844.3       60.9                    0.08
44              806.1  845.19   856.7       50.6                    0.06
45              868.4  868.40   868.4        0.0                    0.00

In [22]:
notas_cn.sort_values(by='Diferenca',ascending=False).head(6)

Minima   Média  Máxima  Diferenca  Porcentagegm_Diferenca
Qtde_Questoes                                                           
0                 0.0    2.05   323.3      323.3                     inf
17              339.1  576.12   628.3      289.2                    0.85
15              327.6  543.99   613.8      286.2                    0.87
16              338.3  560.55   621.1      282.8                    0.84
19              363.6  602.84   646.4      282.8                    0.78
14              330.3  526.85   606.7      276.4                    0.84

In [18]:
df_notas_cn['Qtde_Questoes'].value_counts()

Qtde_Questoes
11    294278
10    283781
12    278659
9     246800
13    244516
14    199813
8     189348
15    155479
7     126058
16    116908
17     85858
6      72203
18     62916
19     46627
20     35857
5      34776
21     27978
22     22142
23     17896
0      16270
24     14845
4      13585
25     12501
26     10665
27      9064
28      7976
29      6673
30      6269
31      5554
32      4760
33      4237
3       4144
34      3804
35      3248
36      2841
37      2478
38      2040
39      1574
40      1098
2       1000
41       749
42       446
1        237
43       215
44        84
45        14
Name: count, dtype: int64

## Ciências Humanas e suas Tecnologias

- A maior diferença de pontos está em 16 acertos, com 293.5;
- A maior porcentaem de diferença está em 16 acertos, com um total de 70%, ou seja, para uma mesma quantidade de acertos, a diferença entre a menor e a maior nota é, no máximo, de 70%;
- A quantidade de questões mais acertadas foram 16, 17, 18, 19 e 20, sedo 17 que teve mais alunos, com um total de 113.636;
- 81 estudantes acertaram todas as questões da prova, tendo um total de 823,0;
- 3.494 estudantes erraram todas as questões da prova.

In [25]:
df_notas_ch = df[['NU_INSCRICAO','TX_GABARITO_CH', 'TX_RESPOSTAS_CH', 'NU_NOTA_CH']]
df_notas_ch['Qtde_Questoes'] = df_notas_ch.apply(lambda row: qtde_questoes_acertadas(row['TX_GABARITO_CH'], row['TX_RESPOSTAS_CH']), axis=1)

minima = df_notas_ch.groupby('Qtde_Questoes')['NU_NOTA_CH'].min()
media = df_notas_ch.groupby('Qtde_Questoes')['NU_NOTA_CH'].mean()
maxima = df_notas_ch.groupby('Qtde_Questoes')['NU_NOTA_CH'].max()
diferenca = maxima - minima
porcentagem = (maxima / minima) - 1

notas_ch = {'Minima' : minima,
        'Média' :  media,
        'Máxima' : maxima,
        'Diferenca' : diferenca,
        'Porcentagegm_Diferenca' : porcentagem}

notas_ch = pd.DataFrame(notas_ch)
notas_ch

Minima   Média  Máxima  Diferenca  Porcentagegm_Diferenca
Qtde_Questoes                                                           
0                 0.0   32.00   293.5      293.5                     inf
1               293.6  300.77   336.5       42.9                    0.15
2               293.2  308.66   368.4       75.2                    0.26
3               293.8  316.41   380.7       86.9                    0.30
4               294.0  324.83   402.6      108.6                    0.37
5               294.7  333.30   409.8      115.1                    0.39
6               294.8  342.52   426.2      131.4                    0.45
7               295.2  353.36   437.2      142.0                    0.48
8               296.4  365.26   448.6      152.2                    0.51
9               296.4  377.83   460.7      164.3                    0.55
10              298.6  391.66   472.9      174.3                    0.58
11              300.2  405.90   483.9      183.7                    0.61
12              306.7  420.85   493.1      186.4                    0.61
13              313.9  435.69   507.2      193.3                    0.62
14              311.7  449.96   509.7      198.0                    0.64
15              320.0  463.81   521.2      201.2                    0.63
16              313.8  476.76   532.4      218.6                    0.70
17              343.1  488.81   538.5      195.4                    0.57
18              340.4  500.01   544.1      203.7                    0.60
19              380.2  510.35   558.5      178.3                    0.47
20              391.6  520.05   563.9      172.3                    0.44
21              397.0  529.21   571.6      174.6                    0.44
22              446.2  537.71   583.0      136.8                    0.31
23              462.3  545.97   588.6      126.3                    0.27
24              479.3  553.92   594.2      114.9                    0.24
25              495.6  561.61   601.9      106.3                    0.21
26              509.6  569.25   609.2       99.6                    0.20
27              499.8  576.72   617.8      118.0                    0.24
28              534.1  584.18   624.7       90.6                    0.17
29              538.8  591.68   631.9       93.1                    0.17
30              546.9  599.44   644.5       97.6                    0.18
31              556.2  607.32   651.0       94.8                    0.17
32              569.3  615.31   656.0       86.7                    0.15
33              566.7  623.97   665.1       98.4                    0.17
34              578.4  632.87   674.2       95.8                    0.17
35              580.7  642.35   684.3      103.6                    0.18
36              600.0  652.76   695.2       95.2                    0.16
37              608.3  663.85   703.1       94.8                    0.16
38              620.3  675.98   716.5       96.2                    0.16
39              630.8  689.13   730.4       99.6                    0.16
40              647.5  704.08   743.4       95.9                    0.15
41              664.9  720.85   757.0       92.1                    0.14
42              679.2  740.08   772.6       93.4                    0.14
43              706.8  762.75   788.0       81.2                    0.11
44              743.1  791.11   805.1       62.0                    0.08
45              823.0  823.00   823.0        0.0                    0.00

In [28]:
notas_ch.sort_values(by='Diferenca',ascending=False).head(6)

Minima   Média  Máxima  Diferenca  Porcentagegm_Diferenca
Qtde_Questoes                                                           
0                 0.0   32.00   293.5      293.5                     inf
16              313.8  476.76   532.4      218.6                    0.70
14              311.7  449.96   509.7      198.0                    0.64
15              320.0  463.81   521.2      201.2                    0.63
13              313.9  435.69   507.2      193.3                    0.62
11              300.2  405.90   483.9      183.7                    0.61

In [27]:
df_notas_ch['Qtde_Questoes'].value_counts()

Qtde_Questoes
17    113636
18    113550
16    112048
19    112009
20    110461
15    109055
21    108550
22    105332
14    103857
23    102035
24     98874
13     96949
25     95861
26     92338
27     88122
12     87840
28     85057
29     81847
30     77749
11     76572
31     73639
32     69642
10     64734
33     64612
34     59842
35     53499
9      50560
36     47222
37     39362
8      37229
38     31699
7      24944
39     23461
40     15846
6      15017
41      9314
5       8210
42      4452
4       3951
0       3494
3       1817
43      1796
2        954
1        693
44       452
45        81
Name: count, dtype: int64

## Matemática e suas Tecnologias

- A maior diferença de pontos está em 17 acertos, com 328,2;
- A maior porcentaem de diferença está em 16 acertos, com um total de 95%, ou seja, para uma mesma quantidade de acertos, a diferença entre a menor e a maior nota é, no máximo, de 95%;
- A quantidade de questões mais acertadas foram 9, 10, 11, 12 e 13, sedo 11 que teve mais alunos, com um total de 200.507;
- 205 estudantes acertaram todas as questões da prova, tendo um total de 823,0;
- 16.519 estudantes erraram todas as questões da prova.

In [29]:
df_notas_mt = df[['TX_GABARITO_MT', 'TX_RESPOSTAS_MT', 'NU_NOTA_MT']]
df_notas_mt['Qtde_Questoes'] = df_notas_mt.apply(lambda row: qtde_questoes_acertadas(row['TX_GABARITO_MT'], row['TX_RESPOSTAS_MT']), axis=1)

minima = df_notas_mt.groupby('Qtde_Questoes')['NU_NOTA_MT'].min()
media = df_notas_mt.groupby('Qtde_Questoes')['NU_NOTA_MT'].mean()
maxima = df_notas_mt.groupby('Qtde_Questoes')['NU_NOTA_MT'].max()
diferenca = maxima - minima
porcentagem = (maxima / minima) - 1

notas_mt = {'Minima' : minima,
        'Média' :  media,
        'Máxima' : maxima,
        'Diferenca' : diferenca,
        'Porcentagegm_Diferenca' : porcentagem}

notas_mt = pd.DataFrame(notas_mt)
notas_mt

Minima   Média  Máxima  Diferenca  Porcentagegm_Diferenca
Qtde_Questoes                                                           
0                 0.0    4.31   328.2      328.2                     inf
1               319.8  335.68   369.6       49.8                    0.16
2               323.7  341.56   399.4       75.7                    0.23
3               321.1  348.38   431.1      110.0                    0.34
4               322.1  355.84   455.0      132.9                    0.41
5               320.7  365.46   478.5      157.8                    0.49
6               321.8  376.05   504.4      182.6                    0.57
7               322.7  388.05   521.7      199.0                    0.62
8               322.7  402.04   540.3      217.6                    0.67
9               327.6  417.73   562.3      234.7                    0.72
10              325.5  435.57   575.5      250.0                    0.77
11              331.1  455.66   592.7      261.6                    0.79
12              332.0  477.37   609.9      277.9                    0.84
13              332.2  500.51   626.4      294.2                    0.89
14              335.8  524.59   637.9      302.1                    0.90
15              343.2  548.03   655.5      312.3                    0.91
16              341.2  570.92   663.8      322.6                    0.95
17              349.7  591.96   676.5      326.8                    0.93
18              374.8  611.25   685.7      310.9                    0.83
19              388.5  628.62   697.6      309.1                    0.80
20              408.0  644.53   701.6      293.6                    0.72
21              446.8  658.51   710.2      263.4                    0.59
22              507.2  671.41   719.7      212.5                    0.42
23              554.4  683.28   734.9      180.5                    0.33
24              573.9  694.69   739.2      165.3                    0.29
25              624.2  705.31   745.2      121.0                    0.19
26              640.6  715.63   756.8      116.2                    0.18
27              642.0  725.69   762.7      120.7                    0.19
28              666.4  735.41   772.7      106.3                    0.16
29              689.4  745.44   784.1       94.7                    0.14
30              696.0  755.31   790.3       94.3                    0.14
31              708.8  765.43   807.6       98.8                    0.14
32              729.1  775.82   818.8       89.7                    0.12
33              730.1  786.25   826.8       96.7                    0.13
34              753.7  797.46   835.2       81.5                    0.11
35              767.2  808.65   844.5       77.3                    0.10
36              782.3  820.39   860.7       78.4                    0.10
37              794.7  832.34   876.4       81.7                    0.10
38              801.9  845.71   885.6       83.7                    0.10
39              821.3  859.52   902.5       81.2                    0.10
40              833.4  874.51   918.8       85.4                    0.10
41              854.1  890.86   935.8       81.7                    0.10
42              870.5  908.31   946.7       76.2                    0.09
43              891.9  928.15   958.6       66.7                    0.07
44              917.8  946.17   958.6       40.8                    0.04
45              958.6  958.60   958.6        0.0                    0.00

In [33]:
notas_mt.sort_values(by='Diferenca',ascending=False).head(6)

Minima   Média  Máxima  Diferenca  Porcentagegm_Diferenca
Qtde_Questoes                                                           
0                 0.0    4.31   328.2      328.2                     inf
16              341.2  570.92   663.8      322.6                    0.95
17              349.7  591.96   676.5      326.8                    0.93
15              343.2  548.03   655.5      312.3                    0.91
14              335.8  524.59   637.9      302.1                    0.90
13              332.2  500.51   626.4      294.2                    0.89

In [32]:
df_notas_mt['Qtde_Questoes'].value_counts()

Qtde_Questoes
11    200507
12    197176
10    192324
13    183840
9     171605
14    166821
15    147586
8     140783
16    130327
17    113561
7     102107
18     98095
19     86257
20     76358
21     67526
6      65482
22     59703
23     53227
24     47034
25     42045
26     36876
5      36459
27     32556
28     28331
29     24847
30     21367
31     18686
4      16960
0      16519
32     16138
33     14043
34     12076
35     10403
36      8992
37      7756
38      6558
3       6199
39      5611
40      4515
41      3582
42      2582
2       1869
43      1511
44       716
1        543
45       205
Name: count, dtype: int64

## 	Linguagens, Códigos e suas Tecnologias

- A maior diferença de pontos está em 17 acertos, com 288,6;
- A maior porcentaem de diferença está em 14 acertos, com um total de 64%, ou seja, para uma mesma quantidade de acertos, a diferença entre a menor e a maior nota é, no máximo, de 64%;
- A quantidade de questões mais acertadas foram 18, 19, 20, 21 e 22, sedo 19 que teve mais alunos, com um total de 124.285;
- 4 estudantes acertaram todas as questões da prova, tendo um total de 823,0;
- 1.013 estudantes erraram todas as questões da prova.

In [40]:
def qtde_questoes_acertadas(str1, str2, idioma):

    if idioma == 0:
        gabarito = str1[:5] + str1[10:]
        tamanho = len(gabarito)
    elif idioma == 1:
        gabarito = str1[5:]
        tamanho = len(gabarito)
    
    contador = 0
    for i in range(tamanho):
        if gabarito[i] == str2[i]:
            contador += 1
    return contador

df_notas_lc = df[['TX_GABARITO_LC', 'TX_RESPOSTAS_LC', 'NU_NOTA_LC', 'TP_LINGUA']]
df_notas_lc['Qtde_Questoes'] = df_notas_lc.apply(lambda row: qtde_questoes_acertadas(row['TX_GABARITO_LC'], row['TX_RESPOSTAS_LC'], row['TP_LINGUA']), axis=1)

minima = df_notas_lc.groupby('Qtde_Questoes')['NU_NOTA_LC'].min()
media = df_notas_lc.groupby('Qtde_Questoes')['NU_NOTA_LC'].mean()
maxima = df_notas_lc.groupby('Qtde_Questoes')['NU_NOTA_LC'].max()
diferenca = maxima - minima
porcentagem = (maxima / minima) - 1

notas_lc = {'Minima' : minima,
        'Média' :  media,
        'Máxima' : maxima,
        'Diferenca' : diferenca,
        'Porcentagegm_Diferenca' : porcentagem}

notas_lc = pd.DataFrame(notas_lc)
notas_lc

Minima   Média  Máxima  Diferenca  Porcentagegm_Diferenca
Qtde_Questoes                                                           
0                 0.0   59.93   288.6      288.6                     inf
1               287.0  295.04   346.1       59.1                    0.21
2               287.6  303.56   367.3       79.7                    0.28
3               288.0  313.39   384.2       96.2                    0.33
4               288.2  321.51   392.8      104.6                    0.36
5               288.7  332.88   408.3      119.6                    0.41
6               289.8  344.60   419.5      129.7                    0.45
7               290.9  357.54   431.8      140.9                    0.48
8               292.0  370.36   442.2      150.2                    0.51
9               294.2  384.33   450.7      156.5                    0.53
10              295.4  398.50   459.9      164.5                    0.56
11              296.7  412.40   471.8      175.1                    0.59
12              302.5  426.33   481.6      179.1                    0.59
13              304.9  439.46   490.4      185.5                    0.61
14              308.1  452.22   503.9      195.8                    0.64
15              318.9  463.91   511.5      192.6                    0.60
16              323.1  475.31   520.7      197.6                    0.61
17              324.2  485.90   530.0      205.8                    0.63
18              366.7  495.89   536.9      170.2                    0.46
19              366.5  505.25   548.1      181.6                    0.50
20              406.9  514.18   555.7      148.8                    0.37
21              399.4  522.81   560.3      160.9                    0.40
22              453.2  531.05   569.4      116.2                    0.26
23              469.9  539.17   578.6      108.7                    0.23
24              481.8  547.14   580.9       99.1                    0.21
25              496.1  555.02   588.7       92.6                    0.19
26              506.0  562.90   598.0       92.0                    0.18
27              514.2  570.79   605.7       91.5                    0.18
28              531.3  578.87   612.6       81.3                    0.15
29              540.5  586.99   619.2       78.7                    0.15
30              547.2  595.35   628.0       80.8                    0.15
31              550.4  603.86   636.1       85.7                    0.16
32              567.8  612.77   642.1       74.3                    0.13
33              571.7  622.02   651.9       80.2                    0.14
34              582.0  631.61   659.5       77.5                    0.13
35              592.8  641.88   670.3       77.5                    0.13
36              599.0  652.78   679.6       80.6                    0.13
37              615.8  664.31   690.2       74.4                    0.12
38              628.8  676.80   704.5       75.7                    0.12
39              640.8  690.11   717.0       76.2                    0.12
40              652.8  704.63   735.5       82.7                    0.13
41              677.2  720.70   749.2       72.0                    0.11
42              689.7  738.23   767.9       78.2                    0.11
43              726.1  758.39   783.3       57.2                    0.08
44              751.9  787.23   803.1       51.2                    0.07
45              820.8  820.80   820.8        0.0                    0.00

In [41]:
notas_lc.sort_values(by='Porcentagegm_Diferenca',ascending=False).head(6)

Minima   Média  Máxima  Diferenca  Porcentagegm_Diferenca
Qtde_Questoes                                                           
0                 0.0   59.93   288.6      288.6                     inf
14              308.1  452.22   503.9      195.8                    0.64
17              324.2  485.90   530.0      205.8                    0.63
16              323.1  475.31   520.7      197.6                    0.61
13              304.9  439.46   490.4      185.5                    0.61
15              318.9  463.91   511.5      192.6                    0.60

In [42]:
df_notas_lc['Qtde_Questoes'].value_counts()

Qtde_Questoes
19    124285
20    123931
18    123142
21    123064
22    120932
17    120461
23    119152
16    115986
24    115393
25    112347
15    111247
26    107906
14    103605
27    102429
28     96819
13     94561
29     90147
12     83536
30     82077
31     74212
11     71690
32     64965
10     57945
33     55649
34     46427
9      44903
35     36763
8      31935
36     28049
7      20933
37     20258
38     13583
6      12164
39      8238
5       6204
40      4474
4       2686
41      2140
3       1119
0       1013
42       802
2        480
1        352
43       221
44        35
45         4
Name: count, dtype: int64

## Resumo dos Dados

- 14 alunos fecharam Ciências da Natureza, enquanto 205 fecharam Matemática;
- 1013 alunos erram todas as questões de Linguagens, enquanto 16.519 erram todas as questões de Matemática;
- A diferença em Linguagens foi de 288,6 pontos, enquanto em Matemática foi 328,2 pontos;
- A diferença, em porcentagem, foi de 64% em Linguagens, enquanto em Matemática foi de 95%;
- A quantidade de acertos foi 11 em Matemática e Ciências da Natureza, enquanto em Linguagens foi 19.

In [55]:
dados = {
    'Area' : ['Ciências da Natureza', 'Ciências Humanas', 'Matemática', 'Linguagens'],
    'Fecharam' : [14, 81, 205, 4],
    'Erraram' : [16270, 3494, 16519, 1013],
    'Diferenca' : [289.2, 293.5, 328.2, 288.6],
    'Diferenca%' : [0.87, 0.7, 0.95, 0.64],
    'Qtde Acertas' : [11, 17, 11, 19]
}

In [56]:
pd.DataFrame(dados)

Area  Fecharam  Erraram  Diferenca  Diferenca%  \
0  Ciências da Natureza        14    16270      289.2        0.87   
1      Ciências Humanas        81     3494      293.5        0.70   
2            Matemática       205    16519      328.2        0.95   
3            Linguagens         4     1013      288.6        0.64   

   Qtde Acertas  
0            11  
1            17  
2            11  
3            19

# Todos os Participantes

### Gênero

In [ ]:
# Tamanho do Gráfico
plt.figure(figsize=(9,6))

# Plotar Gráfico
ax = sns.countplot(df, x="TP_SEXO", color='#1e90ff')

# Adicionar Titulo
ax.set_title('Gênero - Todos os Participantes - ENEM 2023', loc='left', fontsize=12)

# Remover a legenda dos Eixos
ax.set_xlabel('')
ax.set_ylabel('')

# Remover Gird
ax.spines[['right', 'left', 'top', 'bottom']].set_visible(False)

# Remover Legenda
plt.yticks([])
# Modificar Legenda
plt.xticks([0, 1], ['Mulher', 'Homem'])

# Total
total = df['TP_SEXO'].count()

# Total
total = df['TP_COR_RACA'].count()

# Adicionar anotações nas barras
ax.bar_label(ax.containers[0], fmt=lambda x: f'{(x/total)*100:0.1f}%')

# Adicionar margens
ax.margins(x=0.1, y=0.2)

# Visualizar o gráfico
plt.show()

### Estado Civil

In [ ]:
# Tamanho do Gráfico
plt.figure(figsize=(9,6))

ax = sns.countplot(df, x="TP_ESTADO_CIVIL", color='#1e90ff')
#palette='Greys'

# Adicionar Titulo
ax.set_title('Estado Civil - Todos os Participantes  - ENEM 2023', loc='left', fontsize=12)

# Remover os Eixos
ax.set_xlabel('')
ax.set_ylabel('')

# Remover Gird
ax.spines[['right', 'left', 'top', 'bottom']].set_visible(False)

# Legendas
plt.yticks([])
plt.xticks([0, 1, 2, 3, 4], ['Não Informado', 'Solteiro', 'Casado', 'Divorciado', 'Viuvo'])

# Total
total = df['TP_ESTADO_CIVIL'].count()

# Total
total = df['TP_COR_RACA'].count()

# Adicionar anotações nas barras
ax.bar_label(ax.containers[0], fmt=lambda x: f'{(x/total)*100:0.1f}%')

# Adicionar margens
ax.margins(x=0.1, y=0.2)

# Visualizar o gráfico
plt.show()

### Nacionalidade

In [ ]:
# Tamanho do Gráfico
plt.figure(figsize=(9,6))

ax = sns.countplot(df, x="TP_NACIONALIDADE", color='#1e90ff')
#palette='Greys'

# Adicionar Titulo
ax.set_title('Nacionalidade - Todos os Participantes  - ENEM 2023', loc='left', fontsize=12)

# Remover os Eixos
ax.set_xlabel('')
ax.set_ylabel('')

# Remover Gird
ax.spines[['right', 'left', 'top', 'bottom']].set_visible(False)

# Remover Legenda
plt.yticks([])
# Modificar Legenda
plt.xticks([0,1,2,3,4], ['Não Informado', 'Brasileiro', 'Naturalizado', 'Estrangeiro', 'Nascido no Exterior'])

# Total
total = df['TP_NACIONALIDADE'].count()

# Total
total = df['TP_COR_RACA'].count()

# Adicionar anotações nas barras
ax.bar_label(ax.containers[0], fmt=lambda x: f'{(x/total)*100:0.1f}%')

# Adicionar margens
ax.margins(x=0.1, y=0.2)

# Visualizar o gráfico
plt.show()

### Raça

In [ ]:
# Tamanho do Gráfico
plt.figure(figsize=(9,6))

ax = sns.countplot(df, x="TP_COR_RACA", color='#1e90ff')
#palette='Greys'

# Adicionar Titulo
ax.set_title('Raça - Todos os Participantes  - ENEM 2023', loc='left', fontsize=12)

# Remover os Eixos
ax.set_xlabel('')
ax.set_ylabel('')

# Remover Gird
ax.spines[['right', 'left', 'top', 'bottom']].set_visible(False)

# Remover Legenda
plt.yticks([])
# Modificar Legenda
plt.xticks([0, 1, 2, 3, 4, 5, 6], ['Não Declarada', 'Branca', 'Preta', 'Parda', 'Amarela', 'Índigena', 'NaN'])

# Total
total = df['TP_COR_RACA'].count()

# Adicionar anotações nas barras
ax.bar_label(ax.containers[0], fmt=lambda x: f'{(x/total)*100:0.1f}%')

# Adicionar margens
ax.margins(x=0.1, y=0.2)

# Visualizar o gráfico
plt.show()

### Tipo de Escola

In [ ]:
# Tamanho do Gráfico
plt.figure(figsize=(9,6))

ax = sns.countplot(df, x="TP_ESCOLA", color='#1e90ff')
#palette='Greys'

# Adicionar Titulo
ax.set_title('Tipo de Escola - Todos os Participantes  - ENEM 2023', loc='left', fontsize=12)

# Remover os Eixos
ax.set_xlabel('')
ax.set_ylabel('')

# Remover Gird
ax.spines[['right', 'left', 'top', 'bottom']].set_visible(False)

# Remover Legenda
plt.yticks([])
# Modificar Legenda
plt.xticks([0, 1, 2], ['Não Declarada', 'Pública', 'Privada'])

# Total
total = df['TP_ESCOLA'].count()

# Adicionar anotações nas barras
ax.bar_label(ax.containers[0], fmt=lambda x: f'{(x/total)*100:0.1f}%')

# Adicionar margens
ax.margins(x=0.1, y=0.2)

# Visualizar o gráfico
plt.show()

### Treineiros

In [ ]:
# Tamanho do Gráfico
plt.figure(figsize=(9,6))

ax = sns.countplot(df, x="IN_TREINEIRO", color='#1e90ff')

# Adicionar Titulo
ax.set_title('Treineiros - Todos os Participantes  - ENEM 2023', loc='left', fontsize=12)

# Remover os Eixos
ax.set_xlabel('')
ax.set_ylabel('')

# Remover Gird
ax.spines[['right', 'left', 'top', 'bottom']].set_visible(False)

# Remover Legenda
plt.yticks([])
# Modificar Legenda
plt.xticks([0, 1], ['Não', 'Sim'])

# Total
total = df['IN_TREINEIRO'].count()

# Adicionar anotações nas barras
ax.bar_label(ax.containers[0], fmt=lambda x: f'{(x/total)*100:0.1f}%')

# Adicionar margens
ax.margins(x=0.1, y=0.2)

# Visualizar o gráfico
plt.show()

### Dependência Administrativa

In [ ]:
# Tamanho do Gráfico
plt.figure(figsize=(9,6))

ax = sns.countplot(df, x="TP_DEPENDENCIA_ADM_ESC", color='#1e90ff')

# Adicionar Titulo
ax.set_title('Dependëncia Administrativa da Escola - Todos os Participantes  - ENEM 2023', loc='left', fontsize=12)

# Remover os Eixos
ax.set_xlabel('')
ax.set_ylabel('')

# Remover Gird
ax.spines[['right', 'left', 'top', 'bottom']].set_visible(False)

# Remover Legenda
plt.yticks([])
# Modificar Legenda
plt.xticks([0, 1, 2, 3], ['Fderal', 'Estadual', 'Municipal', 'Privada'])

# Total
total = df['TP_DEPENDENCIA_ADM_ESC'].count()

# Adicionar anotações nas barras
ax.bar_label(ax.containers[0], fmt=lambda x: f'{(x/total)*100:0.1f}%')

# Adicionar margens
ax.margins(x=0.1, y=0.2)

# Visualizar o gráfico
plt.show()

### Localização da Escola

In [ ]:
# Tamanho do Gráfico
plt.figure(figsize=(9,6))

ax = sns.countplot(df, x="TP_LOCALIZACAO_ESC", color='#1e90ff')

# Adicionar Titulo
ax.set_title('Localização da Escola - Todos os Participantes  - ENEM 2023', loc='left', fontsize=12)

# Remover os Eixos
ax.set_xlabel('')
ax.set_ylabel('')

# Remover Gird
ax.spines[['right', 'left', 'top', 'bottom']].set_visible(False)

# Remover Legenda
plt.yticks([])
# Modificar Legenda
plt.xticks([0, 1], ['Urbana', 'Rural'])

# Total
total = df['TP_LOCALIZACAO_ESC'].count()

# Adicionar anotações nas barras
ax.bar_label(ax.containers[0], fmt=lambda x: f'{(x/total)*100:0.1f}%')

# Adicionar margens
ax.margins(x=0.1, y=0.2)

# Visualizar o gráfico
plt.show()

### Participantes por Estado

In [ ]:
# Tamanho do Gráfico
plt.figure(figsize=(15,6))

ax = sns.countplot(df, x="SG_UF_PROVA", color='#1e90ff', order=df['SG_UF_PROVA'].value_counts().index)

# Adicionar Titulo
ax.set_title('Participante por Estado - Todos os Participantes  - ENEM 2023', loc='left', fontsize=12)

# Remover os Eixos
ax.set_xlabel('')
ax.set_ylabel('')

# Remover Gird
ax.spines[['right', 'left', 'top', 'bottom']].set_visible(False)

# Remover Legenda
plt.yticks([])
# Modificar Legenda
#plt.xticks([0, 1], ['Urbana', 'Rural'])

# Total
total = df['SG_UF_PROVA'].count()

# Adicionar anotações nas barras
ax.bar_label(ax.containers[0], fmt=lambda x: f'{(x/total)*100:0.1f}%')

# Adicionar margens
ax.margins(x=0, y=0.2)

# Visualizar o gráfico
plt.show()

In [ ]:
df['W_Media'].mean()

In [ ]:
df2['W_Media'].mean()

In [ ]:

sns.histplot(data=df, x="W_Media", bins=30)

# 1% Mais Altas

In [ ]:
# Separar as média 1% mais altas

df2 = df.sort_values(by='W_Media', ascending=False).head(int(df.shape[0]*0.01))
df2

### Gênero

In [ ]:
# Tamanho do Gráfico
plt.figure(figsize=(9,6))

# Plotar Gráfico
ax = sns.countplot(df2, x="TP_SEXO", color='#1e90ff')

# Adicionar Titulo
ax.set_title('Gênero - 1% dos Participantes - ENEM 2023', loc='left', fontsize=12)

# Remover a legenda dos Eixos
ax.set_xlabel('')
ax.set_ylabel('')

# Remover Gird
ax.spines[['right', 'left', 'top', 'bottom']].set_visible(False)

# Remover Legenda
plt.yticks([])
# Modificar Legenda
plt.xticks([0, 1], ['Mulher', 'Homem'])

# Total
total = df2['TP_SEXO'].count()

# Adicionar anotações nas barras
ax.bar_label(ax.containers[0], fmt=lambda x: f'{(x/total)*100:0.1f}%')

# Adicionar margens
ax.margins(x=0.1, y=0.2)

# Visualizar o gráfico
plt.show()

### Estado Civil

In [ ]:
# Tamanho do Gráfico
plt.figure(figsize=(9,6))

ax = sns.countplot(df2, x="TP_ESTADO_CIVIL", color='#1e90ff')
#palette='Greys'

# Adicionar Titulo
ax.set_title('Estado Civil - 1% dos Participantes - ENEM 2023', loc='left', fontsize=12)

# Remover os Eixos
ax.set_xlabel('')
ax.set_ylabel('')

# Remover Gird
ax.spines[['right', 'left', 'top', 'bottom']].set_visible(False)

# Legendas
plt.yticks([])
plt.xticks([0, 1, 2, 3, 4], ['Não Informado', 'Solteiro', 'Casado', 'Divorciado', 'Viuvo'])

# Total
total = df2['TP_ESTADO_CIVIL'].count()

# Adicionar anotações nas barras
ax.bar_label(ax.containers[0], fmt=lambda x: f'{(x/total)*100:0.1f}%')

# Adicionar margens
ax.margins(x=0.1, y=0.2)

# Visualizar o gráfico
plt.show()

### Raça

In [ ]:
# Tamanho do Gráfico
plt.figure(figsize=(9,6))

ax = sns.countplot(df2, x="TP_COR_RACA", color='#1e90ff')
#palette='Greys'

# Adicionar Titulo
ax.set_title('Raça - 1% dos Participantes - ENEM 2023', loc='left', fontsize=12)

# Remover os Eixos
ax.set_xlabel('')
ax.set_ylabel('')

# Remover Gird
ax.spines[['right', 'left', 'top', 'bottom']].set_visible(False)

# Remover Legenda
plt.yticks([])
# Modificar Legenda
plt.xticks([0, 1, 2, 3, 4, 5, 6], ['Não Declarada', 'Branca', 'Preta', 'Parda', 'Amarela', 'Índigena', 'NaN'])

# Total
total = df2['TP_COR_RACA'].count()

# Adicionar anotações nas barras
ax.bar_label(ax.containers[0], fmt=lambda x: f'{(x/total)*100:0.1f}%')

# Adicionar margens
ax.margins(x=0.1, y=0.2)

# Visualizar o gráfico
plt.show()

### Participantes por Estado

In [ ]:
# Tamanho do Gráfico
plt.figure(figsize=(15,6))

ax = sns.countplot(df2, x="SG_UF_PROVA", color='#1e90ff', order=df2['SG_UF_PROVA'].value_counts().index)

# Adicionar Titulo
ax.set_title('Participante por Estado - 1% dos Participantes - ENEM 2023', loc='left', fontsize=12)

# Remover os Eixos
ax.set_xlabel('')
ax.set_ylabel('')

# Remover Gird
ax.spines[['right', 'left', 'top', 'bottom']].set_visible(False)

# Remover Legenda
plt.yticks([])
# Modificar Legenda
#plt.xticks([0, 1], ['Urbana', 'Rural'])

# Total
total = df2['SG_UF_PROVA'].count()

# Adicionar anotações nas barras
ax.bar_label(ax.containers[0], fmt=lambda x: f'{(x/total)*100:0.1f}%')

# Adicionar margens
ax.margins(x=0, y=0.2)

# Visualizar o gráfico
plt.show()

# Notas

Comparar a média de todos os participantes com os participantes que estão entre 1% com a média mais alta

### Nota Média

In [ ]:
# Tamanho do Gráfico
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 6))

# 
ax1 = sns.histplot(data=df, x="W_Media", bins=30, ax=ax1)


# Adicionar Titulo
ax1.set_title('NOTA MÉDIA - TODOS OS PARTICIPANTES', loc='left', fontsize=12)

# Adicionar linha da média
ax1.axvline(df['W_Media'].mean(), color='black', linestyle='--', linewidth=2)

# Remover os Eixos
ax1.set_xlabel('')
ax1.set_ylabel('')

# Remover Gird
ax1.spines[['right', 'left', 'top', 'bottom']].set_visible(False)

# Legendas
ax1.yaxis.set_ticks([])

# Adicionar margens
ax1.margins(x=0.1, y=0.2)

#
ax2 = sns.histplot(data=df2, x="W_Media", bins=30, ax=ax2)

# Adicionar Titulo
ax2.set_title('NOTA MÉDIA - 1% DOS PARTICIPANTES', loc='left', fontsize=12)

# Adicionar linha da média
ax2.axvline(df2['W_Media'].mean(), color='black', linestyle='--', linewidth=2)

# Remover os Eixos
ax2.set_xlabel('')
ax2.set_ylabel('')

# Remover Gird
ax2.spines[['right', 'left', 'top', 'bottom']].set_visible(False)

# Legendas
ax2.yaxis.set_ticks([])

# Adicionar margens
ax2.margins(x=0.1, y=0.1)

# Visualizar o gráfico
plt.show()

### Nota em Matemática e Suas Tecnologias

In [ ]:
# Tamanho do Gráfico
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 6))

# 
ax1 = sns.histplot(data=df, x="NU_NOTA_MT", bins=30, ax=ax1)


# Adicionar Titulo
ax1.set_title('NOTA MÉDIA - TODOS OS PARTICIPANTES', loc='left', fontsize=12)

# Adicionar linha da média
ax1.axvline(df['NU_NOTA_MT'].mean(), color='black', linestyle='--', linewidth=2)

# Remover os Eixos
ax1.set_xlabel('')
ax1.set_ylabel('')

# Remover Gird
ax1.spines[['right', 'left', 'top', 'bottom']].set_visible(False)

# Legendas
ax1.yaxis.set_ticks([])

# Adicionar margens
ax1.margins(x=0.1, y=0.2)

#
ax2 = sns.histplot(data=df2, x="NU_NOTA_MT", bins=30, ax=ax2)

# Adicionar Titulo
ax2.set_title('NOTA MÉDIA - 1% DOS PARTICIPANTES', loc='left', fontsize=12)

# Adicionar linha da média
ax2.axvline(df2['NU_NOTA_MT'].mean(), color='black', linestyle='--', linewidth=2)

# Remover os Eixos
ax2.set_xlabel('')
ax2.set_ylabel('')

# Remover Gird
ax2.spines[['right', 'left', 'top', 'bottom']].set_visible(False)

# Legendas
ax2.yaxis.set_ticks([])

# Adicionar margens
ax2.margins(x=0.1, y=0.1)

# Visualizar o gráfico
plt.show()

### Nota em Ciências da Natureza

In [ ]:
# Tamanho do Gráfico
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 6))

# 
ax1 = sns.histplot(data=df, x="NU_NOTA_CN", bins=30, ax=ax1)

# Adicionar Titulo
ax1.set_title('NOTA MÉDIA - TODOS OS PARTICIPANTES', loc='left', fontsize=12)

# Adicionar linha da média
ax1.axvline(df['NU_NOTA_CN'].mean(), color='black', linestyle='--', linewidth=2)

# Remover os Eixos
ax1.set_xlabel('')
ax1.set_ylabel('')

# Remover Gird
ax1.spines[['right', 'left', 'top', 'bottom']].set_visible(False)

# Legendas
ax1.yaxis.set_ticks([])

# Adicionar margens
ax1.margins(x=0.1, y=0.2)

#
ax2 = sns.histplot(data=df2, x="NU_NOTA_CN", bins=30, ax=ax2)

# Adicionar Titulo
ax2.set_title('NOTA MÉDIA - 1% DOS PARTICIPANTES', loc='left', fontsize=12)

# Adicionar linha da média
ax2.axvline(df2['NU_NOTA_CN'].mean(), color='black', linestyle='--', linewidth=2)

# Remover os Eixos
ax2.set_xlabel('')
ax2.set_ylabel('')

# Remover Gird
ax2.spines[['right', 'left', 'top', 'bottom']].set_visible(False)

# Legendas
ax2.yaxis.set_ticks([])

# Adicionar margens
ax2.margins(x=0.1, y=0.1)

# Visualizar o gráfico
plt.show()

### Nota em Ciências Humanas

In [ ]:
# Tamanho do Gráfico
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 6))

# 
ax1 = sns.histplot(data=df, x="NU_NOTA_CH", bins=30, ax=ax1)

# Adicionar Titulo
ax1.set_title('NOTA MÉDIA - TODOS OS PARTICIPANTES', loc='left', fontsize=12)

# Adicionar linha da média
ax1.axvline(df['NU_NOTA_CH'].mean(), color='black', linestyle='--', linewidth=2)

# Remover os Eixos
ax1.set_xlabel('')
ax1.set_ylabel('')

# Remover Gird
ax1.spines[['right', 'left', 'top', 'bottom']].set_visible(False)

# Legendas
ax1.yaxis.set_ticks([])

# Adicionar margens
ax1.margins(x=0.1, y=0.2)

#
ax2 = sns.histplot(data=df2, x="NU_NOTA_CH", bins=30, ax=ax2)

# Adicionar Titulo
ax2.set_title('NOTA MÉDIA - 1% DOS PARTICIPANTES', loc='left', fontsize=12)

# Adicionar linha da média
ax2.axvline(df2['NU_NOTA_CH'].mean(), color='black', linestyle='--', linewidth=2)

# Remover os Eixos
ax2.set_xlabel('')
ax2.set_ylabel('')

# Remover Gird
ax2.spines[['right', 'left', 'top', 'bottom']].set_visible(False)

# Legendas
ax2.yaxis.set_ticks([])

# Adicionar margens
ax2.margins(x=0.1, y=0.1)

# Visualizar o gráfico
plt.show()

### Nota em Linguagem e Suas Tecnologias

In [ ]:
# Tamanho do Gráfico
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 6))

# 
ax1 = sns.histplot(data=df, x="NU_NOTA_LC", bins=30, ax=ax1)


# Adicionar Titulo
ax1.set_title('NOTA MÉDIA - TODOS OS PARTICIPANTES', loc='left', fontsize=12)

# Adicionar linha da média
ax1.axvline(df['NU_NOTA_LC'].mean(), color='black', linestyle='--', linewidth=2)

# Remover os Eixos
ax1.set_xlabel('')
ax1.set_ylabel('')

# Remover Gird
ax1.spines[['right', 'left', 'top', 'bottom']].set_visible(False)

# Legendas
ax1.yaxis.set_ticks([])

# Adicionar margens
ax1.margins(x=0.1, y=0.2)

#
ax2 = sns.histplot(data=df2, x="NU_NOTA_LC", bins=30, ax=ax2)

# Adicionar Titulo
ax2.set_title('NOTA MÉDIA - 1% DOS PARTICIPANTES', loc='left', fontsize=12)

# Adicionar linha da média
ax2.axvline(df2['NU_NOTA_LC'].mean(), color='black', linestyle='--', linewidth=2)

# Remover os Eixos
ax2.set_xlabel('')
ax2.set_ylabel('')

# Remover Gird
ax2.spines[['right', 'left', 'top', 'bottom']].set_visible(False)

# Legendas
ax2.yaxis.set_ticks([])

# Adicionar margens
ax2.margins(x=0.1, y=0.1)

# Visualizar o gráfico
plt.show()